<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class JobsApi {

	function __construct($apiClient) {
	  $this->apiClient = $apiClient;
	}

  /**
	 * getJobsMap
	 * Return a map of jobId to URI
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return jobStatusMap
	 */

   public function getJobsMap($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'jobStatusMap');
  		return $responseObject;

      }
  /**
	 * getJobsMapHead
	 * Return a map of jobId to URI
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getJobsMapHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * postJob
	 * Schedules the submitted job
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * body, string: ReportRequest (optional)
   * @return ReportResponse
	 */

   public function postJob($Authorization=null, $Accept=null, $body=null) {

  		//parse inputs
  		$resourcePath = "/jobs";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "POST";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'ReportResponse');
  		return $responseObject;

      }
  /**
	 * getDeletedJobsCatalog
	 * Return a catalog of deleted jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobsCatalogResponse
	 */

   public function getDeletedJobsCatalog($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/deleted";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobsCatalogResponse');
  		return $responseObject;

      }
  /**
	 * getDeletedJobsCatalogHead
	 * Return a catalog of deleted jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getDeletedJobsCatalogHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/deleted";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getFailedJobsCatalog
	 * Return a catalog of failed jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobsCatalogResponse
	 */

   public function getFailedJobsCatalog($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/failed";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobsCatalogResponse');
  		return $responseObject;

      }
  /**
	 * getFailedJobsCatalogHead
	 * Return a catalog of failed jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getFailedJobsCatalogHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/failed";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * purgeExpired
	 * Purges expired jobs
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function purgeExpired($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/expired";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "DELETE";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getExpiredJobsCatalog
	 * Return a catalog of expired jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobsCatalogResponse
	 */

   public function getExpiredJobsCatalog($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/expired";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobsCatalogResponse');
  		return $responseObject;

      }
  /**
	 * getExpiredJobsCatalogHead
	 * Return a catalog of expired jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getExpiredJobsCatalogHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/expired";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getCompleteJobsCatalog
	 * Return a catalog of complete jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobsCatalogResponse
	 */

   public function getCompleteJobsCatalog($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/complete";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobsCatalogResponse');
  		return $responseObject;

      }
  /**
	 * getCompleteJobsCatalogHead
	 * Return a catalog of complete jobs' JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getCompleteJobsCatalogHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/complete";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getJobsCatalog
	 * Return a catalog of all JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobsCatalogResponse
	 */

   public function getJobsCatalog($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/catalog";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobsCatalogResponse');
  		return $responseObject;

      }
  /**
	 * getJobsCatalogHead
	 * Return a catalog of all JobEntities
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getJobsCatalogHead($Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/catalog";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        //make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getJobEntity
	 * Return a JobEntity
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return JobEntity
	 */

   public function getJobEntity($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'JobEntity');
  		return $responseObject;

      }
  /**
	 * getJobEntityHead
	 * Return a JobEntity
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getJobEntityHead($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getJobResult
	 * Returns a stream containing the result content for the given Job ID
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return byte
	 */

   public function getJobResult($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/result";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'byte');
  		return $responseObject;

      }
  /**
	 * getJobResultHead
	 * Returns a stream containing the result content for the given Job ID
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * @return 
	 */

   public function getJobResultHead($job_id=null, $Authorization=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/result";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * deleteReport
	 * Purges report output for a given Job ID
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return DeleteResponse
	 */

   public function deleteReport($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/result";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "DELETE";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'DeleteResponse');
  		return $responseObject;

      }
  /**
	 * getResultDetail
	 * Retrieves details for output from a given jobId
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return ReportEntity
	 */

   public function getResultDetail($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/result/detail";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'ReportEntity');
  		return $responseObject;

      }
  /**
	 * getResultDetailHead
	 * Retrieves details for output from a given jobId
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getResultDetailHead($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/result/detail";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  /**
	 * getJobStatus
	 * Return StatusResponse for given jobId
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return StatusResponse
	 */

   public function getJobStatus($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/status";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "GET";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      if(! $response){
          return null;
        }

  		$responseObject = $this->apiClient->deserialize($response,
  		                                                'StatusResponse');
  		return $responseObject;

      }
  /**
	 * getJobStatusHead
	 * Return StatusResponse for given jobId
   * job_id, string: job_id (optional)
   * Authorization, string: Authorization (optional)
   * Accept, string: Accept (optional)
   * @return 
	 */

   public function getJobStatusHead($job_id=null, $Authorization=null, $Accept=null) {

  		//parse inputs
  		$resourcePath = "/jobs/{job_id}/status";
  		$resourcePath = str_replace("{format}", "json", $resourcePath);
  		$method = "HEAD";
      $queryParams = array();
      $headerParams = array();

      if($Authorization != null) {
                $headerParams['Authorization'] = $this->apiClient->toHeaderValue($Authorization);
            }
        if($Accept != null) {
                $headerParams['Accept'] = $this->apiClient->toHeaderValue($Accept);
            }
        if($job_id != null) {
  			$resourcePath = str_replace("{" . "job_id" . "}",
  			                            $this->apiClient->toPathValue($job_id), $resourcePath);
  		}
  		//make the API Call
      if (! isset($body)) {
        $body = null;
      }
  		$response = $this->apiClient->callAPI($resourcePath, $method,
  		                                      $queryParams, $body,
  		                                      $headerParams);


      }
  
}

